services:
  comfyui:
    build:
      context: .
      dockerfile: dockerfile
    image: comfyui:latest
    container_name: comfyui
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - D:\test:/app/ComfyUI/models
    ports:
      - "8188:8188"
    runtime: nvidia
    #network_mode: host